# Generated by Django 6.0.3 on 2026-03-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('bin_height_cm', models.FloatField(default=100.0)),
                ('current_distance_cm', models.FloatField(default=0.0)),
                ('fill_percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('EMPTY', 'Empty'), ('PARTIAL', 'Partial'), ('FULL', 'Full'), ('OFFLINE', 'Offline')], default='EMPTY', max_length=20)),
                ('threshold_percentage', models.FloatField(default=80.0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BinReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_cm', models.FloatField()),
                ('fill_percentage', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='bins.bin')),
            ],
        ),
    ]
