# Generated by Django 6.0.3 on 2026-03-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='device_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
