# Generated by Django 6.0.3 on 2026-03-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_bin_device_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id_attempted', models.CharField(blank=True, max_length=50, null=True)),
                ('provided_device_key', models.CharField(blank=True, max_length=128, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
