# Generated by Django 6.0.3 on 2026-03-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='telegram_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
